jobs:
  include:
    - stage: build application
      install:
        - cp .travis.settings.xml $HOME/.m2/settings.xml
      script:
        - mvn deploy
    - stage: static code analysis
      addons:
        sonarcloud:
          organization: hrsfire-github
          token: $SONAR_TOKEN
      script:
        - mvn org.jacoco:jacoco-maven-plugin:prepare-agent javadoc:javadoc verify sonar:sonar
        - cd ..
        - "git clone https://${TRAVIS_GITHUB_TOKEN}@github.com/hrsFire/Random-Image-Generator-Docs.git"
        - rm -rf Random-Image-Generator-Docs/generated/jacoco-ut Random-Image-Generator-Docs/generated/jacoco-it Random-Image-Generator-Docs/generated/apidocs
        - cp -r Random-Image-Generator-Server/target/site/jacoco-ut Random-Image-Generator-Docs/generated/
        - cp -r Random-Image-Generator-Server/target/site/jacoco-ut Random-Image-Generator-Docs/generated/
        - cp -r Random-Image-Generator-Server/target/site/apidocs Random-Image-Generator-Docs/generated/
        - cd Random-Image-Generator-Docs/generated
        - git add --all
        - git commit -am "update documentation"
        - git push "https://${TRAVIS_GITHUB_TOKEN}@github.com/hrsFire/Random-Image-Generator-Docs.git" master
    - stage: deploy to staging
      script: skip
      deploy: &heroku
        provider: heroku
        app: random-image-generator-api-sta
        api_key: $HEROKU_API_KEY
    - stage: automatic user acceptance and performance tests on staging
      script:
        - cd ..
        - "git clone https://${TRAVIS_GITHUB_TOKEN}@github.com/hrsFire/Random-Image-Generator-Tests.git"
        - cd Random-Image-Generator-Tests
        - mvn verify
        - cd ..
        - "git clone https://${TRAVIS_GITHUB_TOKEN}@github.com/hrsFire/Random-Image-Generator-Docs.git"
        - rm -rf Random-Image-Generator-Docs/generated/cukedoctor Random-Image-Generator-Docs/generated/walk_through_*.mp4
        - cp -r Random-Image-Generator-Tests/target/cukedoctor Random-Image-Generator-Docs/generated/
        - rm -rf Random-Image-Generator-Docs/generated/jmeter
        - cp -r Random-Image-Generator-Tests/target/jmeter/reports/performance* Random-Image-Generator-Docs/generated/jmeter
        - cd Random-Image-Generator-Docs/generated
        - python2 ../../Random-Image-Generator-Tests/Cucumber/get_testingbot_video.py
        - git add --all
        - git commit -am "update documentation"
        - git push "https://${TRAVIS_GITHUB_TOKEN}@github.com/hrsFire/Random-Image-Generator-Docs.git" master
    - stage: deploy to production
      script: skip
      deploy:
        <<: *heroku
        app: random-image-generator-api-fhv
